<?php
/**
 * TodoApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.25
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * TodoApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TodoApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteTodoItem
     *
     * Removes the todo resource..
     *
     */
    public function testDeleteTodoItem()
    {
    }

    /**
     * Test case for getTodoCollection
     *
     * Retrieves the collection of todo resources..
     *
     */
    public function testGetTodoCollection()
    {
    }

    /**
     * Test case for getTodoItem
     *
     * Retrieves a todo resource..
     *
     */
    public function testGetTodoItem()
    {
    }

    /**
     * Test case for postTodoCollection
     *
     * Creates a todo resource..
     *
     */
    public function testPostTodoCollection()
    {
    }

    /**
     * Test case for putTodoItem
     *
     * Replaces the todo resource..
     *
     */
    public function testPutTodoItem()
    {
    }
}
